// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: device.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllDevice = `-- name: CountAllDevice :one
SELECT count(*) FROM device
`

func (q *Queries) CountAllDevice(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllDevice)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :exec
INSERT INTO device (token, name, location)
VALUES ($1, $2, $3)
`

type CreateDeviceParams struct {
	Token    string
	Name     string
	Location string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.Exec(ctx, createDevice, arg.Token, arg.Name, arg.Location)
	return err
}

const getAllDevice = `-- name: GetAllDevice :many
SELECT id, token, name, location, created_at, updated_at, deleted_by, deleted_at FROM device
`

func (q *Queries) GetAllDevice(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, getAllDevice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Name,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllNameDevice = `-- name: GetAllNameDevice :many
SELECT id, name FROM device
`

type GetAllNameDeviceRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) GetAllNameDevice(ctx context.Context) ([]GetAllNameDeviceRow, error) {
	rows, err := q.db.Query(ctx, getAllNameDevice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllNameDeviceRow
	for rows.Next() {
		var i GetAllNameDeviceRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceByToken = `-- name: GetDeviceByToken :one
SELECT id, token, name, location, created_at, updated_at, deleted_by, deleted_at FROM device where token = $1 LIMIT 1
`

func (q *Queries) GetDeviceByToken(ctx context.Context, token string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByToken, token)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedBy,
		&i.DeletedAt,
	)
	return i, err
}

const toggleDeleteDevice = `-- name: ToggleDeleteDevice :exec
UPDATE device SET
deleted_by = CASE WHEN deleted_by IS NULL THEN $1::UUID ELSE NULL END,
deleted_at = CASE WHEN deleted_at IS NULL THEN CURRENT_TIMESTAMP ELSE NULL
END WHERE id = $2
`

type ToggleDeleteDeviceParams struct {
	DeletedBy pgtype.UUID
	ID        pgtype.UUID
}

func (q *Queries) ToggleDeleteDevice(ctx context.Context, arg ToggleDeleteDeviceParams) error {
	_, err := q.db.Exec(ctx, toggleDeleteDevice, arg.DeletedBy, arg.ID)
	return err
}

const updateDevice = `-- name: UpdateDevice :exec
UPDATE device
SET name = $1, location = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3
`

type UpdateDeviceParams struct {
	Name     string
	Location string
	ID       pgtype.UUID
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) error {
	_, err := q.db.Exec(ctx, updateDevice, arg.Name, arg.Location, arg.ID)
	return err
}
