basePath: /
definitions:
  constants.AuthVerificationStep:
    enum:
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - AuthVerificationRegister
    - AuthVerificationOtp
    - AuthVerificationDone
  models.AuthToken:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      phone_number:
        type: string
      role:
        $ref: '#/definitions/sql.Role'
    type: object
  request.AuthVerification:
    properties:
      token:
        example: 2YbPyusF2G06BFQLamoKFXvGgPd
        type: string
    type: object
  response.AuthVerification:
    properties:
      step:
        $ref: '#/definitions/constants.AuthVerificationStep'
      token:
        type: string
    type: object
  response.BaseResponse:
    properties:
      code:
        example: 999
        type: integer
      data: {}
      message:
        example: Message!
        type: string
    type: object
  sql.Role:
    enum:
    - admin
    - guest
    type: string
    x-enum-varnames:
    - RoleAdmin
    - RoleGuest
info:
  contact:
    email: rizal.arfiyan.23@gmail.com
    name: Rizal Arfiyan
    url: https://rizalrfiyan.com
  description: This is a API documentation of BE Revend
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: BE Revend API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Base Home
      operationId: get-base-home
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.BaseResponse'
      summary: Get Base Home based on parameter
      tags:
      - home
  /auth/google:
    get:
      description: Auth Google Redirection
      operationId: get-auth-google
      responses:
        "307":
          description: Temporary Redirect
        "500":
          description: Internal Server Error
      summary: Get Auth Google Redirection based on parameter
      tags:
      - auth
  /auth/google/callback:
    get:
      description: Auth Google Callback Redirection
      operationId: get-auth-google-callback
      responses:
        "307":
          description: Temporary Redirect
        "500":
          description: Internal Server Error
      summary: Get Auth Google Callback Redirection based on parameter
      tags:
      - auth
  /auth/me:
    get:
      consumes:
      - application/json
      description: Auth Me
      operationId: get-auth-me
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.AuthToken'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.BaseResponse'
      security:
      - AccessToken: []
      summary: Get Auth Me based on parameter
      tags:
      - auth
  /auth/verification:
    post:
      consumes:
      - application/json
      description: Auth Verification
      operationId: post-auth-verification
      parameters:
      - description: Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AuthVerification'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.AuthVerification'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.BaseResponse'
      summary: Post Auth Verification based on parameter
      tags:
      - auth
  /health:
    get:
      consumes:
      - application/json
      description: Base Health
      operationId: get-base-health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.BaseResponse'
      summary: Get Base Health based on parameter
      tags:
      - home
securityDefinitions:
  AccessToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
